<?xml version="1.0"?>
<package format="3">
  <name>iswv_canopen</name>
  <version>0.1.0</version>
  <description>Portable C++17 CANopen and iSWV steering wheel driver library.</description>
  <maintainer email="1326898804@qq.com">kkkk</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>communication</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
